name: CI

on:
  push:
    branches:
    - main   
  pull_request:
    branches:
    - main    
    - feature/**    

jobs:
  build:
    name: Build & Test & Publish NuGet
    runs-on: 'ubuntu-latest'
    env:
      config: 'Release'
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1
        
    - name: Add github nuget registry
      run: dotnet nuget add source --username fathi.chabane@gmail.com --password Info**1987 --store-password-in-clear-text --name github "https://nuget.pkg.github.com/crown12/index.json"      
      
    - name: Restore dependencies
      run: dotnet restore --locked-mode
      working-directory: ./EmptyProject
      
    - name: Build
      run: dotnet build --configuration ${{ env.config }} --no-restore
      working-directory: ./EmptyProject
      
    - name: Create the package
      # if: ${{ github.ref == 'refs/heads/develop' }}
      run: dotnet pack --configuration ${{ env.config }} --no-build --no-restore
      working-directory: ./EmptyProject
 
    - name: Publish the package to GPR
      # if: ${{ github.ref == 'refs/heads/develop' }}
      run: dotnet nuget push "**/*.nupkg" --source "https://nuget.pkg.github.com/crown12/index.json" --password Info**1987 --skip-duplicate
